### ISSUE TITLE
Only with wallet

### ISSUE THREAD

**Issue by b4zz4** [samlich/peertube-plugin-web-monetization#1]
Is it possible to use it directly from a BTC or other cryptocurrency portfolio?
I thought of an address: btc, ltc, etc. and check address wallet
So you don't need intermediary platforms

**Comment by samlich** [comment]
The payments are made by the [Interledger network](https://interledger.org/), the address must be an [Interledger payment pointer](https://interledger.org/rfcs/0026-payment-pointers/). I don't know the specifics about how payments are processed, but I think arbitrary assets can be sent as payment (Coil seems to use XRP). The intermediaries convert those assets to USD (or other desired currency).

I think the way to do something like that is to create a service which accepts an address in the path of the payment pointer (e.g. $whatever.com/btc/1hgfrunuuhg) which will accumulate, convert, and then forward the payments. So, it is not currently possible, but a service could be created.

**Comment by samlich** [comment]
See #4
